package com.leadmilers.saathi.report

import android.content.ContentValues
import android.content.Context
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.view.View
import com.github.mikephil.charting.charts.LineChart
import com.github.mikephil.charting.components.XAxis
import com.github.mikephil.charting.data.*
import com.github.mikephil.charting.formatter.IndexAxisValueFormatter
import com.leadmilers.saathi.data.entity.RiskAssessment
import com.leadmilers.saathi.data.entity.SymptomLog
import com.leadmilers.saathi.ml.RiskScorer
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.*

object ReportGenerator {

    private const val PAGE_W = 595
    private const val PAGE_H = 842
    private const val MARGIN = 40f
    private const val HEADER_H = 50f
    private const val FOOTER_H = 30f
    private const val CONTENT_TOP = MARGIN + HEADER_H
    private const val CONTENT_BOTTOM = PAGE_H - MARGIN - FOOTER_H

    // Colors
    private val colorPrimary = Color.parseColor("#6A1B9A")
    private val colorLow     = Color.parseColor("#4CAF50")
    private val colorMod     = Color.parseColor("#FF9800")
    private val colorHigh    = Color.parseColor("#F44336")
    private val colorCrit    = Color.parseColor("#9C27B0")
    private val colorText    = Color.parseColor("#212121")
    private val colorLight   = Color.parseColor("#F3E5F5")

    suspend fun generate(
        context: Context,
        riskAssessments: List<RiskAssessment>,
        symptomLogs: List<SymptomLog>,
        patientName: String = "Patient"
    ): String = withContext(Dispatchers.IO) {
        val dateStr = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())
        val fileName = "Saathi_Report_$dateStr.pdf"

        val doc = PdfDocument()
        val latest = riskAssessments.firstOrNull()

        drawPage1(doc, latest, patientName, dateStr)
        drawPage2(doc, context, symptomLogs, riskAssessments)
        drawPage3(doc, symptomLogs)

        val path = saveDocument(context, doc, fileName)
        doc.close()
        path
    }

    // ── Page 1: Summary ──────────────────────────────────────────────────
    private fun drawPage1(
        doc: PdfDocument, assessment: RiskAssessment?,
        patientName: String, dateStr: String
    ) {
        val page = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, 1).create())
        val c = page.canvas
        drawHeader(c)
        drawFooter(c)

        var y = CONTENT_TOP + 20f

        // Patient info block
        val blockPaint = Paint().apply { color = colorLight }
        c.drawRoundRect(RectF(MARGIN, y, PAGE_W - MARGIN, y + 90f), 8f, 8f, blockPaint)
        c.drawText("Patient: $patientName", MARGIN + 16f, y + 28f, textPaint(18f, bold = true))
        c.drawText("Report date: $dateStr", MARGIN + 16f, y + 54f, textPaint(14f))
        c.drawText("Generated by Saathi — On-device PCOS Risk Tracker", MARGIN + 16f, y + 76f, textPaint(11f, color = Color.GRAY))
        y += 110f

        // Risk score card
        val level = assessment?.riskLevel ?: "Unknown"
        val score = assessment?.totalScore ?: 0
        val levelColor = riskColor(level)
        c.drawRoundRect(RectF(MARGIN, y, PAGE_W - MARGIN, y + 130f), 12f, 12f,
            Paint().apply { color = levelColor })
        c.drawText("PCOS RISK LEVEL", MARGIN + 20f, y + 30f,
            textPaint(13f, color = Color.WHITE))
        c.drawText(level.uppercase(), MARGIN + 20f, y + 75f,
            textPaint(32f, bold = true, color = Color.WHITE))
        c.drawText("Score: $score / 12", MARGIN + 20f, y + 108f,
            textPaint(16f, color = Color.WHITE))
        y += 150f

        // Risk score breakdown
        c.drawText("Score Breakdown", MARGIN, y, textPaint(16f, bold = true))
        y += 24f
        val breakdown = listOf(
            "Cycle irregularity" to (assessment?.cycleScore ?: 0),
            "Androgenic acne (TFLite AUC 0.94)" to (assessment?.acneScore ?: 0),
            "Fatigue / voice energy drop" to (assessment?.fatigueScore ?: 0),
            "Physical symptoms" to (assessment?.physicalScore ?: 0)
        )
        for ((label, pts) in breakdown) {
            val barW = (PAGE_W - MARGIN * 2 - 160f)
            val fill = if (pts > 0) (pts.toFloat() / 12f * barW) else 2f
            c.drawRoundRect(RectF(MARGIN + 160f, y - 12f, MARGIN + 160f + barW, y + 4f),
                4f, 4f, Paint().apply { color = Color.LTGRAY })
            c.drawRoundRect(RectF(MARGIN + 160f, y - 12f, MARGIN + 160f + fill, y + 4f),
                4f, 4f, Paint().apply { color = colorPrimary })
            c.drawText(label, MARGIN, y, textPaint(12f))
            c.drawText("+$pts", PAGE_W - MARGIN - 30f, y, textPaint(12f, bold = true))
            y += 30f
        }
        y += 10f

        // Clinical guidance
        c.drawText("Clinical Guidance", MARGIN, y, textPaint(16f, bold = true))
        y += 22f
        val guidance = when {
            level.contains("Critical", ignoreCase = true) ->
                "Immediate gynaecological consultation recommended.\nMultiple strong PCOS indicators detected."
            level.contains("High", ignoreCase = true) ->
                "Gynaecological evaluation advised within 2-4 weeks.\nSignificant PCOS risk factors present."
            level.contains("Moderate", ignoreCase = true) ->
                "Monitor symptoms over next 4 weeks.\nConsider evaluation if symptoms persist."
            else ->
                "Continue monitoring. Low risk indicators at this time."
        }
        for (line in guidance.lines()) {
            c.drawText(line, MARGIN, y, textPaint(12f))
            y += 18f
        }

        doc.finishPage(page)
    }

    // ── Page 2: 4-week trend chart ────────────────────────────────────────
    private fun drawPage2(
        doc: PdfDocument, context: Context,
        symptomLogs: List<SymptomLog>, riskAssessments: List<RiskAssessment>
    ) {
        val page = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, 2).create())
        val c = page.canvas
        drawHeader(c)
        drawFooter(c)

        var y = CONTENT_TOP + 20f
        c.drawText("4-Week Trend Analysis", MARGIN, y, textPaint(18f, bold = true))
        y += 30f

        val chartBitmap = renderChart(context, symptomLogs, riskAssessments)
        val chartW = (PAGE_W - MARGIN * 2).toInt()
        val chartH = 360
        val scaled = Bitmap.createScaledBitmap(chartBitmap, chartW, chartH, true)
        c.drawBitmap(scaled, MARGIN, y, null)
        y += chartH + 20f

        // Legend
        c.drawText("Chart Legend:", MARGIN, y, textPaint(12f, bold = true))
        y += 18f
        val legend = listOf(
            Color.parseColor("#E91E63") to "Acne score (TFLite)",
            Color.parseColor("#2196F3") to "Voice energy",
            Color.parseColor("#FF9800") to "Fatigue (normalized)",
            Color.parseColor("#9C27B0") to "Risk score (normalized)"
        )
        for ((col, lbl) in legend) {
            c.drawRoundRect(RectF(MARGIN, y - 10f, MARGIN + 24f, y + 4f),
                3f, 3f, Paint().apply { color = col })
            c.drawText(lbl, MARGIN + 32f, y, textPaint(11f))
            y += 20f
        }

        doc.finishPage(page)
    }

    private fun renderChart(
        context: Context,
        symptomLogs: List<SymptomLog>,
        riskAssessments: List<RiskAssessment>
    ): Bitmap {
        val logs = symptomLogs.takeLast(28).reversed()
        val fmt = SimpleDateFormat("MM/dd", Locale.getDefault())
        val labels = logs.map { fmt.format(Date(it.date)) }

        fun entries(values: List<Float>) =
            values.mapIndexed { i, v -> Entry(i.toFloat(), v) }

        val acneSet = LineDataSet(entries(logs.map { it.acneScore }), "Acne").apply {
            color = Color.parseColor("#E91E63"); setDrawCircles(false); lineWidth = 2f
            setDrawValues(false); mode = LineDataSet.Mode.CUBIC_BEZIER
        }
        val voiceSet = LineDataSet(entries(logs.map { it.voiceEnergyScore }), "Voice").apply {
            color = Color.parseColor("#2196F3"); setDrawCircles(false); lineWidth = 2f
            setDrawValues(false); mode = LineDataSet.Mode.CUBIC_BEZIER
        }
        val fatigueSet = LineDataSet(entries(logs.map { it.fatigue / 5f }), "Fatigue").apply {
            color = Color.parseColor("#FF9800"); setDrawCircles(false); lineWidth = 2f
            setDrawValues(false); mode = LineDataSet.Mode.CUBIC_BEZIER
        }
        val riskMap = riskAssessments.associate { it.date to it.totalScore }
        val riskVals = logs.map { log ->
            val closest = riskMap.keys.minByOrNull { kotlin.math.abs(it - log.date) }
            (riskMap[closest] ?: 0) / 12f
        }
        val riskSet = LineDataSet(entries(riskVals), "Risk").apply {
            color = Color.parseColor("#9C27B0"); setDrawCircles(false); lineWidth = 2.5f
            setDrawValues(false); mode = LineDataSet.Mode.CUBIC_BEZIER
        }

        val chart = LineChart(context)
        chart.data = LineData(acneSet, voiceSet, fatigueSet, riskSet)
        chart.description.isEnabled = false
        chart.legend.isEnabled = false
        chart.axisRight.isEnabled = false
        chart.xAxis.apply {
            position = XAxis.XAxisPosition.BOTTOM
            valueFormatter = IndexAxisValueFormatter(labels)
            labelRotationAngle = -45f
            granularity = 1f
            setLabelCount(minOf(7, labels.size), false)
        }
        chart.axisLeft.apply { axisMinimum = 0f; axisMaximum = 1f }
        chart.setBackgroundColor(Color.WHITE)
        chart.extraBottomOffset = 20f

        val w = 1000; val h = 500
        chart.measure(
            View.MeasureSpec.makeMeasureSpec(w, View.MeasureSpec.EXACTLY),
            View.MeasureSpec.makeMeasureSpec(h, View.MeasureSpec.EXACTLY)
        )
        chart.layout(0, 0, w, h)
        chart.invalidate()

        val bmp = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
        chart.draw(Canvas(bmp))
        return bmp
    }

    // ── Page 3: Symptom log table ─────────────────────────────────────────
    private fun drawPage3(doc: PdfDocument, symptomLogs: List<SymptomLog>) {
        val page = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, 3).create())
        val c = page.canvas
        drawHeader(c)
        drawFooter(c)

        var y = CONTENT_TOP + 20f
        c.drawText("Symptom Log — Last 30 Days", MARGIN, y, textPaint(18f, bold = true))
        y += 28f

        // Table header
        val cols = listOf("Date", "Acne", "Voice", "Fatigue", "Skin D.", "Wt Gain", "Hair")
        val colW = floatArrayOf(100f, 65f, 65f, 65f, 65f, 70f, 65f)
        var x = MARGIN
        c.drawRect(RectF(MARGIN, y - 14f, PAGE_W - MARGIN, y + 6f),
            Paint().apply { color = colorPrimary })
        for ((i, col) in cols.withIndex()) {
            c.drawText(col, x + 4f, y, textPaint(11f, bold = true, color = Color.WHITE))
            x += colW[i]
        }
        y += 18f

        val fmt = SimpleDateFormat("MM/dd", Locale.getDefault())
        val logs = symptomLogs.take(30)
        logs.forEachIndexed { idx, log ->
            if (y > CONTENT_BOTTOM - 20f) return@forEachIndexed
            val rowColor = if (idx % 2 == 0) Color.parseColor("#F8F0FF") else Color.WHITE
            c.drawRect(RectF(MARGIN, y - 13f, PAGE_W - MARGIN, y + 5f),
                Paint().apply { color = rowColor })
            x = MARGIN
            val cells = listOf(
                fmt.format(Date(log.date)),
                "%.2f".format(log.acneScore),
                "%.2f".format(log.voiceEnergyScore),
                "${log.fatigue}/5",
                if (log.skinDarkening) "Yes" else "No",
                if (log.weightGain) "Yes" else "No",
                if (log.hairIssues) "Yes" else "No"
            )
            for ((i, cell) in cells.withIndex()) {
                c.drawText(cell, x + 4f, y, textPaint(10f))
                x += colW[i]
            }
            y += 18f
        }
        y += 20f

        // Clinical notes section
        if (y < CONTENT_BOTTOM - 100f) {
            c.drawText("Clinical Notes", MARGIN, y, textPaint(16f, bold = true))
            y += 22f
            c.drawRect(RectF(MARGIN, y, PAGE_W - MARGIN, y + 120f),
                Paint().apply { color = Color.TRANSPARENT; style = Paint.Style.STROKE
                    strokeWidth = 1f; color = Color.LTGRAY })
            c.drawText("(Space for doctor's annotations)", MARGIN + 10f, y + 20f,
                textPaint(11f, color = Color.LTGRAY))
        }

        doc.finishPage(page)
    }

    // ── Shared elements ───────────────────────────────────────────────────
    private fun drawHeader(c: Canvas) {
        c.drawRect(RectF(0f, 0f, PAGE_W.toFloat(), 4f), Paint().apply { color = colorPrimary })
        c.drawText(
            "Saathi PCOS Risk Report — For Medical Professional Review",
            MARGIN, MARGIN + 28f, textPaint(13f, bold = true, color = colorPrimary)
        )
        c.drawLine(MARGIN, MARGIN + 38f, PAGE_W - MARGIN, MARGIN + 38f,
            Paint().apply { color = Color.LTGRAY; strokeWidth = 1f })
    }

    private fun drawFooter(c: Canvas) {
        c.drawLine(MARGIN, (PAGE_H - MARGIN - 22f), PAGE_W - MARGIN, (PAGE_H - MARGIN - 22f),
            Paint().apply { color = Color.LTGRAY; strokeWidth = 1f })
        c.drawText(
            "Not a diagnostic tool. Consult a qualified medical professional.",
            MARGIN, (PAGE_H - MARGIN - 6f), textPaint(10f, color = Color.GRAY)
        )
    }

    private fun riskColor(level: String) = when {
        level.contains("Critical", ignoreCase = true) -> colorCrit
        level.contains("High", ignoreCase = true) -> colorHigh
        level.contains("Moderate", ignoreCase = true) -> colorMod
        else -> colorLow
    }

    private fun textPaint(
        size: Float,
        bold: Boolean = false,
        color: Int = colorText
    ) = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        textSize = size
        typeface = if (bold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
        this.color = color
    }

    // ── Save to Downloads ─────────────────────────────────────────────────
    private fun saveDocument(context: Context, doc: PdfDocument, fileName: String): String {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val values = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)!!
            context.contentResolver.openOutputStream(uri)!!.use { doc.writeTo(it) }
            uri.toString()
        } else {
            val file = File(
                Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
                fileName
            )
            FileOutputStream(file).use { doc.writeTo(it) }
            file.absolutePath
        }
    }
}
